dist: trusty
language: java
sudo: false
jdk:
  - oraclejdk8

git:
  depth: 2 #clone repository to a maximum depth of 2 commits

script: "mvn clean install -Dmaven.javadoc.skip=true -B -V"

before_install:
  - chmod +x mvnw

after_success:
  - mvn clean integration-test
  - bash <(curl -s https://codecov.io/bash)